pipeline {
  agent any
   
  stages {
    stage("Build image and container") {
      steps {
        sh 'docker build -t pythonapp:1.0 .'
        sh 'docker run -d -p 32769:5000 pythonapp:1.0'
      }
    }
  }
}
