pipeline {
  agent any

  stages{
    stage('Build'){
      steps{
        sh 'docker build -t mypythonapp /var/lib/jenkins/workspace/practise-lab1/docker-practise/lab1/Jenkinsfile' 
        sh 'docker run -d -p 1234:1234 mypythonapp'
}
}
}
}
