def getDockerTag() {
 def tag = sh script: 'git rev-parse HEAD', returnStdout: true 
 return tag
}

pipeline {
    agent any
    environment {
          Docker_tag = getDockerTag()
      }
    stages {
          stage('build and push Docker image'){
		 steps {
			script{
				sh 'docker build -f ./docker-training/Dockerfile -t sreddy12333/devops-training:$Docker_tag .'
				withCredentials([string(credentialsId: 'sreddy12333', variable: 'dockerHub-12')]) {
					sh 'docker login -u sreddy12333 -p $dockerHub-12'
					sh 'docker push sreddy12333/devops-training:$Docker_tag'
				}
			}
		 }
	  }
   }
}
