
pipeline {
  agent any

  stages{
    stage('Build and deploy multiple container using docker compose'){
      steps{
        sh 'docker-compose -f ./dockerdeploy/docker-compose.yml'

      }
    }
  }
}

