
pipeline {
  agent any

  stages{
    stage('Build and deploy multiple container using docker compose'){
      steps{
        sh 'docker-compose up -d ./dockerdeploy/docker-compose.yml .'

      }
    }
  }
}

