
pipeline {
  agent any

  stages{
    stage('Build and deploy multiple container using docker compose'){
      steps{
        sh 'docker-compose  -f ./docker-compose-demo/docker-compose.yml up -d'
      }
    }
  }
}

