pipeline {
  agent any

  stages{
    stage('Build Nginx Image'){
      steps{
        sh 'docker build -f ./nginx/Dockerfile -t nginxvenkata:1.0 .'
        sh 'docker run -d -p 3244:80 nginxvenkata:1.0'

      }
    stage("Tag the image") {
        steps {
        sh 'docker tag nginxvenkata:latest venkata/nginxtask:1.0'
        }
      }   
    }
  }
}
