pipeline {
  agent any
   
  stages {
    stage("Build image and container") {
      steps {
        sh 'docker build -t mypythonapp:0.1 /var/lib/jenkins/workspace/Lab5/docker-training/docker-exercise/lab5'
        sh 'docker run -d -p 32769:5000 mypythonapp:0.1'
      }
    }
  }
}
