pipeline {
  agent any
   
  stages {
    stage("Build image and container") {
      steps {
        sh 'docker build -t mypythonapp:0.1 /var/lib/jenkins/workspace/Python-job/docker-practice/lab1'
        sh 'docker run -d -p 32769:5000 mypythonapp:0.1'
      }
    }
  }
}
