pipeline {
  agent any
   
  stages {
    stage("Build image and run container") {
      steps {
        sh 'docker build -t myjavaapp:0.1 /var/lib/jenkins/workspace/practise-lab2/lab2'
        sh 'docker run -d -p 32770:5000 myjavaapp:0.1'
      }
    }
  }
}
