pipeline {
environment {
registry = "daidasunny/nginxsunil"
registryCredential = 'dockerhub_id'
}
  agent any

  stages {
    stage("Build image and container") {
      steps {
        sh 'docker build -f ./Dockerlab-nginx/Dockerfile -t nginxsunil:latest .'
        sh 'docker tag nginxsunil:latest daidasunny/nginxtask:sunil'
        sh 'docker run -d -p 3244:80 daidasunny/nginxtask:sunil'
      }
    }
    stage('Deploy Image') {
       steps {
           withCredentials([usernamePassword(credentialsId: 'dockerhub_id', passwordVariable: 'dockerhub_idPassword', usernameVariable: 'dockerhub_idUser')]) {
               sh 'docker push daidasunny/nginxtask:sunil'
           }
       }
    }
  }
}
